# @name configure_environment
POST http://localhost:8000/environment/configure/
Content-Type: application/json
Accept: application/json

{
  "n_players": 6,
  "starting_stack_size": 2000
}


###
# @name reset_environment
POST http://localhost:8000/environment/1/reset
Content-Type: application/json
Accept: application/json

{
  "env_id": 1,
  "stack_sizes": {
    "stack_p0": 0,
    "stack_p1": 140,
    "stack_p2": 800,
    "stack_p3": 0,
    "stack_p4": 0,
    "stack_p5": 200
  }
}

###
# @name step_environment
GET http://localhost:8000/environment/1/step/?action=0&action_how_much=-1.0
